[package]
name = "pactus-daemon"
version = "0.1.0"
edition = "2021"
authors = ["Pactus <info@pactus.org>"]


[dependencies]
pactus = {path = "../../pactus"}
pactus-types = { path = "../../types" }
structopt = "0.3"
pretty_env_logger = "0.5"
ctrlc = "3.2"
anyhow = "1.0"
dirs = "5.0"
serde = "1.0"
serde_json = "1.0"
serde_plain = "1.0"
toml = "0.8"
async-std = "1.10"
lazy_static = "1.4"

[dev-dependencies]
tempfile = "3.3"